# Generated by Django 5.2.8 on 2026-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('recording', 'Recording'), ('homework', 'Homework Sheet')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('grade', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
