# Generated by Django 5.2.8 on 2026-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exam', 'Exam'), ('homework', 'Homework')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('total_possible', models.FloatField(default=100)),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
